import './globals.css'
import { Providers } from "./providers";
import NavMenu from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons:{
    icon:"/favicon.svg",
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-slate-800">
      <Providers>
      <header >
            <NavMenu />
          </header>
        <main className="min-h-screen ">
          {children}
        </main>
        <Footer/>
        </Providers>
      </body>
    </html>
  )
}
